### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 2

### ISSUE THREAD

**Issue by rhalp10** [rhalp10/E-Trade-E-Commerce#1]
**XAMPP Version:** 7.3.12 / PHP 7.3.12 
**VM415:**
```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function mcrypt_encrypt() in C:\xampp\htdocs\Lenard\data-md5.php:8
Stack trace:
#0 C:\xampp\htdocs\E-Trade-E-Commerce\data-login.php(50): encryptIt('dsadasd')
#1 C:\xampp\htdocs\E-Trade-E-Commerce\data-login.php(28): login()
#2 {main}
  thrown in <b>C:\xampp\htdocs\E-Trade-E-Commerce\data-md5.php</b> on line <b>8</b><br />
```

**Comment by rhalp10** [comment]
This function has been DEPRECATED as of PHP 7.1.0. Relying on this function is highly discouraged.
